name: asx
description: asx is a lightweight library for parsing asx documents from document string.
version: 1.0.8
homepage: https://github.com/Andromo-App-Maker/asx

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  xml: 6.3.0
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.1
